# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-04 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20170404_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default=datetime.datetime(2017, 4, 4, 17, 43, 43, 35912, tzinfo=utc), null=True, upload_to=''),
        ),
    ]
