# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 21:17
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20170404_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('100'), default_currency='EUR', max_digits=10),
        ),
    ]
