# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20170409_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'approved'), ('r', 'rejected')], default='p', max_length=1),
        ),
    ]
