# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
