# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170314_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tag',
            new_name='tags',
        ),
    ]
