# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170314_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='#content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='#content'),
        ),
    ]
