# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
