# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 18, 13, 39, 798590)),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 18, 13, 39, 799042)),
        ),
    ]
