# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170309_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 18, 14, 28, 544957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 18, 14, 28, 545407, tzinfo=utc)),
        ),
    ]
